"""Golden-corpus gate (Task 8): ARCHITECTURE §6 thresholds over pairs.json.

The corpus is GENERATED by scripts/gen_golden_pairs.py (mechanically, from
the unverified seed lexicon -- every pair is flagged ``needs_human`` for
Robel). Pairs marked ``known_fail`` are honest records of current engine
limits: a separate test asserts they KEEP failing, so an engine improvement
forces a conscious corpus regeneration instead of silently changing the
gate.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest

from habesha_names.match.full import match

_ROOT = Path(__file__).resolve().parents[1]
_CORPUS = Path(__file__).parent / "golden" / "pairs.json"
_DATA = json.loads(_CORPUS.read_text(encoding="utf-8"))
_PAIRS: list[dict[str, object]] = _DATA["pairs"]

SAME_MIN: float = _DATA["thresholds"]["same_min"]
DIFFERENT_MAX: float = _DATA["thresholds"]["different_max"]

_ACTIVE = [entry for entry in _PAIRS if not entry.get("known_fail")]
_KNOWN_FAIL = [entry for entry in _PAIRS if entry.get("known_fail")]


def _meets_expectation(entry: dict[str, object]) -> tuple[bool, float]:
    score = float(match(str(entry["a"]), str(entry["b"])))
    if entry["expected"] == "same":
        return score >= SAME_MIN, score
    return score <= DIFFERENT_MAX, score


def _pair_id(entry: dict[str, object]) -> str:
    return f"{entry['expected']}:{entry['a']}|{entry['b']}"


# --- corpus shape -------------------------------------------------------------


def test_corpus_size_meets_plan_minimum() -> None:
    assert len(_PAIRS) >= 150


def test_thresholds_match_architecture() -> None:
    # ARCHITECTURE §6: same-person >= 0.85, different-person <= 0.6.
    assert SAME_MIN == 0.85
    assert DIFFERENT_MAX == 0.60


def test_every_pair_is_flagged_for_human_review() -> None:
    assert all(entry.get("needs_human") is True for entry in _PAIRS)


def test_no_duplicate_pairs() -> None:
    keys = [frozenset((str(entry["a"]), str(entry["b"]))) for entry in _PAIRS]
    assert len(keys) == len(set(keys))


def test_schema_of_every_entry() -> None:
    for entry in _PAIRS:
        assert isinstance(entry["a"], str) and entry["a"]
        assert isinstance(entry["b"], str) and entry["b"]
        assert entry["expected"] in ("same", "different")
        assert isinstance(entry["source"], str) and entry["source"]
        assert isinstance(entry["score_at_generation"], float)


def test_corpus_has_both_outcomes_and_scripts() -> None:
    expectations = {entry["expected"] for entry in _PAIRS}
    assert expectations == {"same", "different"}
    assert any(not str(entry["a"]).isascii() for entry in _PAIRS)  # fidel present


def test_corpus_file_is_current() -> None:
    # Regenerating must reproduce the committed file byte-for-byte, so the
    # corpus cannot drift from the generator (or be hand-edited unnoticed).
    result = subprocess.run(
        [sys.executable, str(_ROOT / "scripts" / "gen_golden_pairs.py"), "--check"],
        capture_output=True,
        text=True,
        encoding="utf-8",
    )
    assert result.returncode == 0, result.stdout + result.stderr


# --- the actual gate ------------------------------------------------------------


@pytest.mark.parametrize("entry", _ACTIVE, ids=_pair_id)
def test_golden_pair(entry: dict[str, object]) -> None:
    ok, score = _meets_expectation(entry)
    bound = f">= {SAME_MIN}" if entry["expected"] == "same" else f"<= {DIFFERENT_MAX}"
    assert ok, f"match({entry['a']!r}, {entry['b']!r}) = {score:.4f}, expected {bound}"


@pytest.mark.parametrize("entry", _KNOWN_FAIL, ids=_pair_id)
def test_known_fail_pair_still_fails(entry: dict[str, object]) -> None:
    # Strict-xfail semantics: if one of these starts passing, regenerate the
    # corpus (which will drop its known_fail marker) rather than letting the
    # gate drift silently.
    ok, score = _meets_expectation(entry)
    assert not ok, (
        f"match({entry['a']!r}, {entry['b']!r}) = {score:.4f} now meets its "
        "threshold -- regenerate tests/golden/pairs.json"
    )
