# GENERATED by scripts/gen_fidel_tables.py -- do not edit by hand.
# Regenerate:      python scripts/gen_fidel_tables.py
# Check freshness: python scripts/gen_fidel_tables.py --check
"""Ethiopic Unicode tables (generated -- do not edit).

Every fidel<->codepoint mapping here is derived programmatically from
``unicodedata.name()`` over the Ethiopic (U+1200-U+137F) and Ethiopic
Supplement (U+1380-U+139F) blocks; nothing is hand-typed.

Vowel orders follow the traditional analysis (ARCHITECTURE 4.1):
1=ä, 2=u, 3=i, 4=a, 5=é, 6=ə/bare, 7=o; order 8 is the labialized/
eighth column (Unicode -WA/-OA/-WAA forms).

Consonant labels are the lowercased Unicode consonant name fragments
except for these overrides: 'TS' -> "ts'". The overrides are unreviewed
linguistic data ("verified": false) -- see the PROGRESS.md human review
queue.
"""

from __future__ import annotations

#: Blocks treated as Ethiopic script, as (first, last) inclusive codepoint
#: pairs. The Extended block is recognized by ``is_ethiopic()`` but has no
#: syllable table in v0.1.
ETHIOPIC_RANGES: tuple[tuple[int, int], ...] = (
    (0x1200, 0x137F),  # Ethiopic
    (0x1380, 0x139F),  # Ethiopic Supplement
    (0x2D80, 0x2DDF),  # Ethiopic Extended
)

#: Vowel order assigned to the labialized/eighth column.
LABIALIZED_ORDER = 8

#: Series base codepoint -> consonant label.
CONSONANT_BY_BASE: dict[int, str] = {
    0x1200: 'h',  # ሀ H
    0x1208: 'l',  # ለ L
    0x1210: 'hh',  # ሐ HH
    0x1218: 'm',  # መ M
    0x1220: 'sz',  # ሠ SZ
    0x1228: 'r',  # ረ R
    0x1230: 's',  # ሰ S
    0x1238: 'sh',  # ሸ SH
    0x1240: 'q',  # ቀ Q
    0x1248: 'qw',  # ቈ QW
    0x1250: 'qh',  # ቐ QH
    0x1258: 'qhw',  # ቘ QHW
    0x1260: 'b',  # በ B
    0x1268: 'v',  # ቨ V
    0x1270: 't',  # ተ T
    0x1278: 'c',  # ቸ C
    0x1280: 'x',  # ኀ X
    0x1288: 'xw',  # ኈ XW
    0x1290: 'n',  # ነ N
    0x1298: 'ny',  # ኘ NY
    0x12A0: 'glottal',  # አ GLOTTAL
    0x12A8: 'k',  # ከ K
    0x12B0: 'kw',  # ኰ KW
    0x12B8: 'kx',  # ኸ KX
    0x12C0: 'kxw',  # ዀ KXW
    0x12C8: 'w',  # ወ W
    0x12D0: 'pharyngeal',  # ዐ PHARYNGEAL
    0x12D8: 'z',  # ዘ Z
    0x12E0: 'zh',  # ዠ ZH
    0x12E8: 'y',  # የ Y
    0x12F0: 'd',  # ደ D
    0x12F8: 'dd',  # ዸ DD
    0x1300: 'j',  # ጀ J
    0x1308: 'g',  # ገ G
    0x1310: 'gw',  # ጐ GW
    0x1318: 'gg',  # ጘ GG
    0x1320: 'th',  # ጠ TH
    0x1328: 'ch',  # ጨ CH
    0x1330: 'ph',  # ጰ PH
    0x1338: "ts'",  # ጸ TS
    0x1340: 'tz',  # ፀ TZ
    0x1348: 'f',  # ፈ F
    0x1350: 'p',  # ፐ P
    0x1358: 'ry',  # ፘ RY
    0x1359: 'my',  # ፙ MY
    0x135A: 'fy',  # ፚ FY
    0x1380: 'mw',  # ᎀ MW
    0x1384: 'bw',  # ᎄ BW
    0x1388: 'fw',  # ᎈ FW
    0x138C: 'pw',  # ᎌ PW
}

#: Syllable codepoint -> (consonant label, vowel order).
SYLLABLES: dict[int, tuple[str, int]] = {
    0x1200: ('h', 1),  # ሀ HA
    0x1201: ('h', 2),  # ሁ HU
    0x1202: ('h', 3),  # ሂ HI
    0x1203: ('h', 4),  # ሃ HAA
    0x1204: ('h', 5),  # ሄ HEE
    0x1205: ('h', 6),  # ህ HE
    0x1206: ('h', 7),  # ሆ HO
    0x1207: ('h', 8),  # ሇ HOA
    0x1208: ('l', 1),  # ለ LA
    0x1209: ('l', 2),  # ሉ LU
    0x120A: ('l', 3),  # ሊ LI
    0x120B: ('l', 4),  # ላ LAA
    0x120C: ('l', 5),  # ሌ LEE
    0x120D: ('l', 6),  # ል LE
    0x120E: ('l', 7),  # ሎ LO
    0x120F: ('l', 8),  # ሏ LWA
    0x1210: ('hh', 1),  # ሐ HHA
    0x1211: ('hh', 2),  # ሑ HHU
    0x1212: ('hh', 3),  # ሒ HHI
    0x1213: ('hh', 4),  # ሓ HHAA
    0x1214: ('hh', 5),  # ሔ HHEE
    0x1215: ('hh', 6),  # ሕ HHE
    0x1216: ('hh', 7),  # ሖ HHO
    0x1217: ('hh', 8),  # ሗ HHWA
    0x1218: ('m', 1),  # መ MA
    0x1219: ('m', 2),  # ሙ MU
    0x121A: ('m', 3),  # ሚ MI
    0x121B: ('m', 4),  # ማ MAA
    0x121C: ('m', 5),  # ሜ MEE
    0x121D: ('m', 6),  # ም ME
    0x121E: ('m', 7),  # ሞ MO
    0x121F: ('m', 8),  # ሟ MWA
    0x1220: ('sz', 1),  # ሠ SZA
    0x1221: ('sz', 2),  # ሡ SZU
    0x1222: ('sz', 3),  # ሢ SZI
    0x1223: ('sz', 4),  # ሣ SZAA
    0x1224: ('sz', 5),  # ሤ SZEE
    0x1225: ('sz', 6),  # ሥ SZE
    0x1226: ('sz', 7),  # ሦ SZO
    0x1227: ('sz', 8),  # ሧ SZWA
    0x1228: ('r', 1),  # ረ RA
    0x1229: ('r', 2),  # ሩ RU
    0x122A: ('r', 3),  # ሪ RI
    0x122B: ('r', 4),  # ራ RAA
    0x122C: ('r', 5),  # ሬ REE
    0x122D: ('r', 6),  # ር RE
    0x122E: ('r', 7),  # ሮ RO
    0x122F: ('r', 8),  # ሯ RWA
    0x1230: ('s', 1),  # ሰ SA
    0x1231: ('s', 2),  # ሱ SU
    0x1232: ('s', 3),  # ሲ SI
    0x1233: ('s', 4),  # ሳ SAA
    0x1234: ('s', 5),  # ሴ SEE
    0x1235: ('s', 6),  # ስ SE
    0x1236: ('s', 7),  # ሶ SO
    0x1237: ('s', 8),  # ሷ SWA
    0x1238: ('sh', 1),  # ሸ SHA
    0x1239: ('sh', 2),  # ሹ SHU
    0x123A: ('sh', 3),  # ሺ SHI
    0x123B: ('sh', 4),  # ሻ SHAA
    0x123C: ('sh', 5),  # ሼ SHEE
    0x123D: ('sh', 6),  # ሽ SHE
    0x123E: ('sh', 7),  # ሾ SHO
    0x123F: ('sh', 8),  # ሿ SHWA
    0x1240: ('q', 1),  # ቀ QA
    0x1241: ('q', 2),  # ቁ QU
    0x1242: ('q', 3),  # ቂ QI
    0x1243: ('q', 4),  # ቃ QAA
    0x1244: ('q', 5),  # ቄ QEE
    0x1245: ('q', 6),  # ቅ QE
    0x1246: ('q', 7),  # ቆ QO
    0x1247: ('q', 8),  # ቇ QOA
    0x1248: ('qw', 1),  # ቈ QWA
    0x124A: ('qw', 3),  # ቊ QWI
    0x124B: ('qw', 4),  # ቋ QWAA
    0x124C: ('qw', 5),  # ቌ QWEE
    0x124D: ('qw', 6),  # ቍ QWE
    0x1250: ('qh', 1),  # ቐ QHA
    0x1251: ('qh', 2),  # ቑ QHU
    0x1252: ('qh', 3),  # ቒ QHI
    0x1253: ('qh', 4),  # ቓ QHAA
    0x1254: ('qh', 5),  # ቔ QHEE
    0x1255: ('qh', 6),  # ቕ QHE
    0x1256: ('qh', 7),  # ቖ QHO
    0x1258: ('qhw', 1),  # ቘ QHWA
    0x125A: ('qhw', 3),  # ቚ QHWI
    0x125B: ('qhw', 4),  # ቛ QHWAA
    0x125C: ('qhw', 5),  # ቜ QHWEE
    0x125D: ('qhw', 6),  # ቝ QHWE
    0x1260: ('b', 1),  # በ BA
    0x1261: ('b', 2),  # ቡ BU
    0x1262: ('b', 3),  # ቢ BI
    0x1263: ('b', 4),  # ባ BAA
    0x1264: ('b', 5),  # ቤ BEE
    0x1265: ('b', 6),  # ብ BE
    0x1266: ('b', 7),  # ቦ BO
    0x1267: ('b', 8),  # ቧ BWA
    0x1268: ('v', 1),  # ቨ VA
    0x1269: ('v', 2),  # ቩ VU
    0x126A: ('v', 3),  # ቪ VI
    0x126B: ('v', 4),  # ቫ VAA
    0x126C: ('v', 5),  # ቬ VEE
    0x126D: ('v', 6),  # ቭ VE
    0x126E: ('v', 7),  # ቮ VO
    0x126F: ('v', 8),  # ቯ VWA
    0x1270: ('t', 1),  # ተ TA
    0x1271: ('t', 2),  # ቱ TU
    0x1272: ('t', 3),  # ቲ TI
    0x1273: ('t', 4),  # ታ TAA
    0x1274: ('t', 5),  # ቴ TEE
    0x1275: ('t', 6),  # ት TE
    0x1276: ('t', 7),  # ቶ TO
    0x1277: ('t', 8),  # ቷ TWA
    0x1278: ('c', 1),  # ቸ CA
    0x1279: ('c', 2),  # ቹ CU
    0x127A: ('c', 3),  # ቺ CI
    0x127B: ('c', 4),  # ቻ CAA
    0x127C: ('c', 5),  # ቼ CEE
    0x127D: ('c', 6),  # ች CE
    0x127E: ('c', 7),  # ቾ CO
    0x127F: ('c', 8),  # ቿ CWA
    0x1280: ('x', 1),  # ኀ XA
    0x1281: ('x', 2),  # ኁ XU
    0x1282: ('x', 3),  # ኂ XI
    0x1283: ('x', 4),  # ኃ XAA
    0x1284: ('x', 5),  # ኄ XEE
    0x1285: ('x', 6),  # ኅ XE
    0x1286: ('x', 7),  # ኆ XO
    0x1287: ('x', 8),  # ኇ XOA
    0x1288: ('xw', 1),  # ኈ XWA
    0x128A: ('xw', 3),  # ኊ XWI
    0x128B: ('xw', 4),  # ኋ XWAA
    0x128C: ('xw', 5),  # ኌ XWEE
    0x128D: ('xw', 6),  # ኍ XWE
    0x1290: ('n', 1),  # ነ NA
    0x1291: ('n', 2),  # ኑ NU
    0x1292: ('n', 3),  # ኒ NI
    0x1293: ('n', 4),  # ና NAA
    0x1294: ('n', 5),  # ኔ NEE
    0x1295: ('n', 6),  # ን NE
    0x1296: ('n', 7),  # ኖ NO
    0x1297: ('n', 8),  # ኗ NWA
    0x1298: ('ny', 1),  # ኘ NYA
    0x1299: ('ny', 2),  # ኙ NYU
    0x129A: ('ny', 3),  # ኚ NYI
    0x129B: ('ny', 4),  # ኛ NYAA
    0x129C: ('ny', 5),  # ኜ NYEE
    0x129D: ('ny', 6),  # ኝ NYE
    0x129E: ('ny', 7),  # ኞ NYO
    0x129F: ('ny', 8),  # ኟ NYWA
    0x12A0: ('glottal', 1),  # አ GLOTTAL A
    0x12A1: ('glottal', 2),  # ኡ GLOTTAL U
    0x12A2: ('glottal', 3),  # ኢ GLOTTAL I
    0x12A3: ('glottal', 4),  # ኣ GLOTTAL AA
    0x12A4: ('glottal', 5),  # ኤ GLOTTAL EE
    0x12A5: ('glottal', 6),  # እ GLOTTAL E
    0x12A6: ('glottal', 7),  # ኦ GLOTTAL O
    0x12A7: ('glottal', 8),  # ኧ GLOTTAL WA
    0x12A8: ('k', 1),  # ከ KA
    0x12A9: ('k', 2),  # ኩ KU
    0x12AA: ('k', 3),  # ኪ KI
    0x12AB: ('k', 4),  # ካ KAA
    0x12AC: ('k', 5),  # ኬ KEE
    0x12AD: ('k', 6),  # ክ KE
    0x12AE: ('k', 7),  # ኮ KO
    0x12AF: ('k', 8),  # ኯ KOA
    0x12B0: ('kw', 1),  # ኰ KWA
    0x12B2: ('kw', 3),  # ኲ KWI
    0x12B3: ('kw', 4),  # ኳ KWAA
    0x12B4: ('kw', 5),  # ኴ KWEE
    0x12B5: ('kw', 6),  # ኵ KWE
    0x12B8: ('kx', 1),  # ኸ KXA
    0x12B9: ('kx', 2),  # ኹ KXU
    0x12BA: ('kx', 3),  # ኺ KXI
    0x12BB: ('kx', 4),  # ኻ KXAA
    0x12BC: ('kx', 5),  # ኼ KXEE
    0x12BD: ('kx', 6),  # ኽ KXE
    0x12BE: ('kx', 7),  # ኾ KXO
    0x12C0: ('kxw', 1),  # ዀ KXWA
    0x12C2: ('kxw', 3),  # ዂ KXWI
    0x12C3: ('kxw', 4),  # ዃ KXWAA
    0x12C4: ('kxw', 5),  # ዄ KXWEE
    0x12C5: ('kxw', 6),  # ዅ KXWE
    0x12C8: ('w', 1),  # ወ WA
    0x12C9: ('w', 2),  # ዉ WU
    0x12CA: ('w', 3),  # ዊ WI
    0x12CB: ('w', 4),  # ዋ WAA
    0x12CC: ('w', 5),  # ዌ WEE
    0x12CD: ('w', 6),  # ው WE
    0x12CE: ('w', 7),  # ዎ WO
    0x12CF: ('w', 8),  # ዏ WOA
    0x12D0: ('pharyngeal', 1),  # ዐ PHARYNGEAL A
    0x12D1: ('pharyngeal', 2),  # ዑ PHARYNGEAL U
    0x12D2: ('pharyngeal', 3),  # ዒ PHARYNGEAL I
    0x12D3: ('pharyngeal', 4),  # ዓ PHARYNGEAL AA
    0x12D4: ('pharyngeal', 5),  # ዔ PHARYNGEAL EE
    0x12D5: ('pharyngeal', 6),  # ዕ PHARYNGEAL E
    0x12D6: ('pharyngeal', 7),  # ዖ PHARYNGEAL O
    0x12D8: ('z', 1),  # ዘ ZA
    0x12D9: ('z', 2),  # ዙ ZU
    0x12DA: ('z', 3),  # ዚ ZI
    0x12DB: ('z', 4),  # ዛ ZAA
    0x12DC: ('z', 5),  # ዜ ZEE
    0x12DD: ('z', 6),  # ዝ ZE
    0x12DE: ('z', 7),  # ዞ ZO
    0x12DF: ('z', 8),  # ዟ ZWA
    0x12E0: ('zh', 1),  # ዠ ZHA
    0x12E1: ('zh', 2),  # ዡ ZHU
    0x12E2: ('zh', 3),  # ዢ ZHI
    0x12E3: ('zh', 4),  # ዣ ZHAA
    0x12E4: ('zh', 5),  # ዤ ZHEE
    0x12E5: ('zh', 6),  # ዥ ZHE
    0x12E6: ('zh', 7),  # ዦ ZHO
    0x12E7: ('zh', 8),  # ዧ ZHWA
    0x12E8: ('y', 1),  # የ YA
    0x12E9: ('y', 2),  # ዩ YU
    0x12EA: ('y', 3),  # ዪ YI
    0x12EB: ('y', 4),  # ያ YAA
    0x12EC: ('y', 5),  # ዬ YEE
    0x12ED: ('y', 6),  # ይ YE
    0x12EE: ('y', 7),  # ዮ YO
    0x12EF: ('y', 8),  # ዯ YOA
    0x12F0: ('d', 1),  # ደ DA
    0x12F1: ('d', 2),  # ዱ DU
    0x12F2: ('d', 3),  # ዲ DI
    0x12F3: ('d', 4),  # ዳ DAA
    0x12F4: ('d', 5),  # ዴ DEE
    0x12F5: ('d', 6),  # ድ DE
    0x12F6: ('d', 7),  # ዶ DO
    0x12F7: ('d', 8),  # ዷ DWA
    0x12F8: ('dd', 1),  # ዸ DDA
    0x12F9: ('dd', 2),  # ዹ DDU
    0x12FA: ('dd', 3),  # ዺ DDI
    0x12FB: ('dd', 4),  # ዻ DDAA
    0x12FC: ('dd', 5),  # ዼ DDEE
    0x12FD: ('dd', 6),  # ዽ DDE
    0x12FE: ('dd', 7),  # ዾ DDO
    0x12FF: ('dd', 8),  # ዿ DDWA
    0x1300: ('j', 1),  # ጀ JA
    0x1301: ('j', 2),  # ጁ JU
    0x1302: ('j', 3),  # ጂ JI
    0x1303: ('j', 4),  # ጃ JAA
    0x1304: ('j', 5),  # ጄ JEE
    0x1305: ('j', 6),  # ጅ JE
    0x1306: ('j', 7),  # ጆ JO
    0x1307: ('j', 8),  # ጇ JWA
    0x1308: ('g', 1),  # ገ GA
    0x1309: ('g', 2),  # ጉ GU
    0x130A: ('g', 3),  # ጊ GI
    0x130B: ('g', 4),  # ጋ GAA
    0x130C: ('g', 5),  # ጌ GEE
    0x130D: ('g', 6),  # ግ GE
    0x130E: ('g', 7),  # ጎ GO
    0x130F: ('g', 8),  # ጏ GOA
    0x1310: ('gw', 1),  # ጐ GWA
    0x1312: ('gw', 3),  # ጒ GWI
    0x1313: ('gw', 4),  # ጓ GWAA
    0x1314: ('gw', 5),  # ጔ GWEE
    0x1315: ('gw', 6),  # ጕ GWE
    0x1318: ('gg', 1),  # ጘ GGA
    0x1319: ('gg', 2),  # ጙ GGU
    0x131A: ('gg', 3),  # ጚ GGI
    0x131B: ('gg', 4),  # ጛ GGAA
    0x131C: ('gg', 5),  # ጜ GGEE
    0x131D: ('gg', 6),  # ጝ GGE
    0x131E: ('gg', 7),  # ጞ GGO
    0x131F: ('gg', 8),  # ጟ GGWAA
    0x1320: ('th', 1),  # ጠ THA
    0x1321: ('th', 2),  # ጡ THU
    0x1322: ('th', 3),  # ጢ THI
    0x1323: ('th', 4),  # ጣ THAA
    0x1324: ('th', 5),  # ጤ THEE
    0x1325: ('th', 6),  # ጥ THE
    0x1326: ('th', 7),  # ጦ THO
    0x1327: ('th', 8),  # ጧ THWA
    0x1328: ('ch', 1),  # ጨ CHA
    0x1329: ('ch', 2),  # ጩ CHU
    0x132A: ('ch', 3),  # ጪ CHI
    0x132B: ('ch', 4),  # ጫ CHAA
    0x132C: ('ch', 5),  # ጬ CHEE
    0x132D: ('ch', 6),  # ጭ CHE
    0x132E: ('ch', 7),  # ጮ CHO
    0x132F: ('ch', 8),  # ጯ CHWA
    0x1330: ('ph', 1),  # ጰ PHA
    0x1331: ('ph', 2),  # ጱ PHU
    0x1332: ('ph', 3),  # ጲ PHI
    0x1333: ('ph', 4),  # ጳ PHAA
    0x1334: ('ph', 5),  # ጴ PHEE
    0x1335: ('ph', 6),  # ጵ PHE
    0x1336: ('ph', 7),  # ጶ PHO
    0x1337: ('ph', 8),  # ጷ PHWA
    0x1338: ("ts'", 1),  # ጸ TSA
    0x1339: ("ts'", 2),  # ጹ TSU
    0x133A: ("ts'", 3),  # ጺ TSI
    0x133B: ("ts'", 4),  # ጻ TSAA
    0x133C: ("ts'", 5),  # ጼ TSEE
    0x133D: ("ts'", 6),  # ጽ TSE
    0x133E: ("ts'", 7),  # ጾ TSO
    0x133F: ("ts'", 8),  # ጿ TSWA
    0x1340: ('tz', 1),  # ፀ TZA
    0x1341: ('tz', 2),  # ፁ TZU
    0x1342: ('tz', 3),  # ፂ TZI
    0x1343: ('tz', 4),  # ፃ TZAA
    0x1344: ('tz', 5),  # ፄ TZEE
    0x1345: ('tz', 6),  # ፅ TZE
    0x1346: ('tz', 7),  # ፆ TZO
    0x1347: ('tz', 8),  # ፇ TZOA
    0x1348: ('f', 1),  # ፈ FA
    0x1349: ('f', 2),  # ፉ FU
    0x134A: ('f', 3),  # ፊ FI
    0x134B: ('f', 4),  # ፋ FAA
    0x134C: ('f', 5),  # ፌ FEE
    0x134D: ('f', 6),  # ፍ FE
    0x134E: ('f', 7),  # ፎ FO
    0x134F: ('f', 8),  # ፏ FWA
    0x1350: ('p', 1),  # ፐ PA
    0x1351: ('p', 2),  # ፑ PU
    0x1352: ('p', 3),  # ፒ PI
    0x1353: ('p', 4),  # ፓ PAA
    0x1354: ('p', 5),  # ፔ PEE
    0x1355: ('p', 6),  # ፕ PE
    0x1356: ('p', 7),  # ፖ PO
    0x1357: ('p', 8),  # ፗ PWA
    0x1358: ('ry', 1),  # ፘ RYA
    0x1359: ('my', 1),  # ፙ MYA
    0x135A: ('fy', 1),  # ፚ FYA
    0x1380: ('mw', 1),  # ᎀ SEBATBEIT MWA
    0x1381: ('mw', 3),  # ᎁ MWI
    0x1382: ('mw', 5),  # ᎂ MWEE
    0x1383: ('mw', 6),  # ᎃ MWE
    0x1384: ('bw', 1),  # ᎄ SEBATBEIT BWA
    0x1385: ('bw', 3),  # ᎅ BWI
    0x1386: ('bw', 5),  # ᎆ BWEE
    0x1387: ('bw', 6),  # ᎇ BWE
    0x1388: ('fw', 1),  # ᎈ SEBATBEIT FWA
    0x1389: ('fw', 3),  # ᎉ FWI
    0x138A: ('fw', 5),  # ᎊ FWEE
    0x138B: ('fw', 6),  # ᎋ FWE
    0x138C: ('pw', 1),  # ᎌ SEBATBEIT PWA
    0x138D: ('pw', 3),  # ᎍ PWI
    0x138E: ('pw', 5),  # ᎎ PWEE
    0x138F: ('pw', 6),  # ᎏ PWE
}

#: (consonant label, vowel order) -> syllable codepoint. A bijection;
#: verified by the generator.
CODEPOINT_BY_SYLLABLE: dict[tuple[str, int], int] = {
    syllable: cp for cp, syllable in SYLLABLES.items()
}
